preserve tktcl function if overriding libread.so directory

diff --git a/espconfig b/espconfig
--- a/espconfig
+++ b/espconfig
@@ -12,15 +12,14 @@ for mod in mbarilib termios .; do
 done
 export CC CFLAGS CXXFLAGS
 rm -f ext/readline/libreadline.so*
-[ "$lib" -o `which dpkg-architecture` ] && {
-  [ "$lib" ] || lib="/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`"
-
-  #link Ruby readline extension with libreadline.5
-  oldReadline=$lib/libreadline.so.5
-  if [ -r $oldReadline ]; then
-    ln -s $oldReadline ext/readline/libreadline.so || exit $?
+[ `which dpkg-architecture` ] && {
+  lib="/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`"
+    #link Ruby readline extension with libreadline.5
+  [ "$readline5" ] || readline5=$lib/libreadline.so.5
+  if [ -r $readline5 ]; then
+    ln -s $readline5 ext/readline/libreadline.so || exit $?
   else
-    echo "WARNING:  Missing $oldReadline  (version 6 is incompatible)" >&2
+    echo "WARNING:  Missing $readline5  (version 6 is incompatible)" >&2
     sleep 5
   fi
 
