Link with libreadline.so.5 under Debian (version 6 is incompatible)
Don't build twice in builtUtils
Bumped date

diff --git a/espconfig b/espconfig
--- a/espconfig
+++ b/espconfig
@@ -1,5 +1,5 @@
 #!/bin/bash
-# configure ESP ruby 1.8.7p352 build for workstation -- 8/5/16 brent@mbari.org
+# configure ESP ruby 1.8.7p352 build for workstation -- 9/1/16 brent@mbari.org
 # for gcc x86 add:
 #  -fno-stack-protector
 # to CFLAGS
@@ -7,18 +7,31 @@
 : ${CFLAGS:="-O2 -g -fno-stack-protector"}
 : ${CXXFLAGS:=$CFLAGS}
 : ${CC:=gcc-4.6}
-for mod in mbarilib termios .; do 
+for mod in mbarilib termios .; do
   [ -r $mod/Makefile ] && make -C $mod MINIRUBY=miniruby distclean
 done
 export CC CFLAGS CXXFLAGS
+rm -f ext/readline/libreadline.so*
 [ `which dpkg-architecture` ] && {
-  arch="/usr/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`"
+  lib="/lib/`dpkg-architecture -qDEB_HOST_MULTIARCH`"
+
+  #link Ruby readline extension with libreadline.5
+  oldReadline=$lib/libreadline.so.5
+  if [ -r $oldReadline ]; then
+    ln -s $oldReadline ext/readline/libreadline.so || exit $?
+  else
+    echo "WARNING:  Missing $oldReadline  (version 6 is incompatible)" >&2
+    sleep 5
+  fi
+
+  #find the proper tcl support file in Debian's multiarch scheme
   tcfg=
-  [ -r "$arch/tclConfig.sh" ] &&
-    tcfg="--with-tclConfig-file=$arch/tclConfig.sh"
-  [ -r "$arch/tkConfig.sh" ] &&
-    tcfg="$tcfg --with-tkConfig-file=$arch/tkConfig.sh"
+  usr="/usr/$lib"
+  [ -r "$usr/tclConfig.sh" ] &&
+    tcfg="--with-tclConfig-file=$usr/tclConfig.sh"
+  [ -r "$usr/tkConfig.sh" ] &&
+    tcfg="$tcfg --with-tkConfig-file=$usr/tkConfig.sh"
 }
-rm -f config.cache configure `find ext -name Makefile` && 
+rm -f config.cache configure `find ext -name Makefile` &&
 autoconf && exec configure --prefix=/opt/mbari \
   --enable-mbari-api --enable-pthread --disable-ucontext $tcfg $@
